### ISSUE TITLE
(discuss) another "real world" idiom in need

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#12]
I write a lot of commandline tools, and I love to be able to have access to the cli options via accessor.

The most common pattern I am gravitating towards for processing options is something like the following; Note: I use hand crafted subcommands (e.g., not `App::Cmd`) and the modulino form extensively:  

```
sub _do_subcommand_X {
  my ($self, @_ARGV) = @_;
  my $o = h2o {}, qw/option1 option2 option3/;
  Getopt::Long::GetOptionsFromArray(\@_ARGV, $o, qw/option1=s option2=i option3/);
  # ...
}
```

I find having accessors, even for non-required flags is what I want. The problem I find lies in the required information in the defining of options, namely: `option1=s`, `option2=i` (and other option descriptors for by G::L).

So what's the issue? The issue is that I'd like to create the list of options once; but that list needs to contain information required by G::L.

What's the solution? I am not sure, but seems there should be some way to. munge a G::L style list so that we could do something, effectively like:

```
sub _do_subcommand_X {
  my ($self, @_ARGV) = @_;
  my @options = (qw/option1=s option2=i option3/);
  my $o = h2o {}, @options;
  Getopt::Long::GetOptionsFromArray(\@_ARGV, $o, @options );
  # ...
}
```

What I am imagining is some special treatment of `@options` by `h2o` to take just the longest "valid" hash key for each item in `@options` staring with `^` (so starting left and going right). In the case above, this would result in `(qw/option1 option2 option3/)`, taking everything from `^` until right up to the first invalid subroutine name character (here, `=`).

Any thoughts here? Might it be related to the key munging we've discussed in other issues?

FWIW, I think this can also be "cookbook'd" like `Config;:Tiny` - but what I am finding is that `Getopt::Long` is falling into the same sort of category as calling for something idiomatic, even if some additional support by `h2o` can be provided.

**Comment by oodler577** [comment]
Update: 'Util::H2O::More::opt2h2o` now exists for this purpose.

```
use Util::H2O::More qw/opt2h2o/;
use [Getopt::Long](https://metacpan.org/pod/Getopt::Long) qw//;
my @opts = (qw/option1=s options2=s@ option3 option4=i o5|option5=s/);
my $o = h2o { option1 => q{foo} }, opt2h2o(@opts);
Getopt::Long::GetOptionsFromArray( @ARGV, $o, @opts );
```

I am sure I missed some of the GO syntax, but it works for the most common cases.

**Comment by haukex** [comment]
This is a good use case to point out. I think you've already said it all in your description; I currently don't see a better way to implement this other than parsing `Getopt::Long` option strings. This is something I would consider outside of the scope of `Util::H2O`, so I think `Util::H2O::More` is a great place for this function.

**Comment by oodler577** [comment]
I am going to go ahead and close this to reduce the current list. Thanks for the reply!
