### ISSUE TITLE
Support custom DESTROY when -clean is on

### ISSUE THREAD

**Issue by haukex** [haukex/Util-H2O#2]
_Originally posted by @oodler577 in https://github.com/haukex/Util-H2O/issues/1#issuecomment-883753125_

> It occurs to me, this could also apply to `DESTROY` - any other normal default methods called if they exist related to `bless`ed things? I suppose another could be `TO_JSON` for use with the `JSON` family of modules.

Thanks for the idea - It's already possible to install a custom `DESTROY` when the `-clean` option is off, but `-clean` is on by default, and it would be possible to support a custom `DESTROY` even when `-clean` is on. I need to think about it a bit more but it should be possible.

As for other methods, it's possible to install any methods you like, there are just a couple that are limited to this module.

**Comment by oodler577** [comment]
Thank you, looking forward to this.

**Comment by haukex** [comment]
Just documenting some of my thoughts on this.

| DESTROY | -meth on | -meth off |
| --- | --- | --- |
| -clean on ⇒ H2O needs DESTROY | DESTROY=>coderef: it would be possible to set up the custom destructor to be called from H2O’s DESTROY; DESTROY=>!coderef: not possible for the reason explained to the right | We couldn't set up an accessor named DESTROY because that conflicts with H2O‘s DESTROY ⇒ hash can‘t contain a key named DESTROY |
| -clean off | DESTROY=>coderef: it would be possible to set up the custom DESTROY; DESTROY=>!coderef: possible, see right | We could set up an accessor for a key named DESTROY; it would get called on destruction |

⇒ IMO, explaining all this in the documentation and testing it is too complicated. Instead, I think I will further limit under which circumstances a key named `DESTROY` is allowed by the module, and add a new option `-destr` or `-destroy`, because that will allow installing a custom `DESTROY` under all circumstances.
