### ISSUE TITLE
feature request: `$h2othing->exists` 

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#7]
I am using `Util::H2O` in "production" and I've come across a couple of things that would be nice to have and prevent me from doing hacky things; this is 1 of 2 (added the 2nd one as another issue #8):

I'd like to be able to do this,

```
  my $h2othing = h2o external_call();
  if ( not $h2othing->exists('someKey') and not $h2othing->someKey ) {
    die q{Missing 'someKey'!\n};
  }
```

The alternative is the ugly,

```
  my $h2othing = h2o external_call();
  if ( not exists $h2othing->{'someKey'} and not $h2othing->someKey  ) {
    die q{Missing 'someKey'!\n};
  }
```

**Comment by haukex** [comment]
Hi, I'm glad to hear you're finding use for the module!

Adding new methods always comes with a caveat: they may mask keys that exist in the hash (which takes precedence, should the module throw an error, etc?), and an `exists` method would IMHO be too simple to be worth it (`sub exists { exists $_[0]->{$_[1]} }`). I personally find `exists $h2othing->{someKey}` just fine, and I don't think the `and not $h2othing->someKey` part is necessary, or am I misunderstanding something? (e.g. are you using `-meth`?)

**Comment by oodler577** [comment]
Thank you :) - I am not using `-meth` directly. I'll take a closer look at it. I might throw something like that in `Util::H2O::More`, a module I threw up on CPAN and am using to provide a `bless` workalike using internally, `Util::H2O`. I tout it as _like if `bless` gave you accessors_.

Anyway, I understand your thoughts. _exists_ could be a hash key, I've even used that one before. Me personally, I am getting hung up on the disruptive use of lower level key access when 99% of it is using clean accessors. I think that one should be able to drop down to the raw key access if needed. I think this is driven by this being `h2o` being almost the perfect tool to take results hash refs from `DBI`, `Web::Scraper`, etc and naturally easily giving them accessors. 

Anyway, thanks for the comment. I will think more about what the overall experience I am going for; I also need to consider this along with #8. Because on one hand, I want to be able to check if a field (and thus an accessor) exists before calling the accessor; on the other hand, I want to be able to have `h2o` be told to "return `undef` if the ref you're givine is `undef`". So it's a matter of degrees of precision over being able to decide what to do with whatever `h2o` gives you.

**Comment by haukex** [comment]
Thanks for the feedback! I thought about it a bit and I think there may be use in a generalized option to add methods to objects, something like `h2o -meths=>{ exists => sub { exists $_[0]->{$_[1]} } }, some_func();`, which would do what you want in this case. I will think about this some more though, since I also don't want to reimplement [`Role::Tiny`](https://metacpan.org/pod/Role::Tiny) or [`Hash::Merge`](https://metacpan.org/pod/Hash::Merge) (both of which you could look into as well if you haven't yet, especially the first in this case). This may be a case for sinply adding more examples to my "Cookbook" in the documentation.

**Comment by oodler577** [comment]
Thank you for the replay! I've been thinking about basically taking taking stuff from the Cookbook and adding, if feasible, them into `Util::H2O::More` - I'll keep an eye on these and if I end up wrapping something up into the ::More module, I will. Also would be delighted to get any feedback on you for ideas about other things to maybe add in there; in this way you can keep `Util::H2O` rather pristine, and offload a lot of the bells and whistles off to `Util::H2O::More` or some other related catch-all.

**Comment by haukex** [comment]
I am currently considering a `-roles` option as a shortcut for adding `Role::Tiny` roles.

In the meantime, I realized your original question has a fairly simple answer: this feature already exists, as provided by [`UNIVERSAL`](https://perldoc.perl.org/UNIVERSAL)'s `can`, which checks for the existence of methods!

**Comment by oodler577** [comment]
I'd like to withdraw this issue. Since you've commented already I will defer to you closing it. I refactored the code where I needed it a tad, and just added an empty key for the thing I wanted to test via `if ($obj->field_thats_undef) { ..`. Ultimately I didn't want to use `UNIVERSAL::can` even though I _could_ (pun not intended but hilarious nonetheless). Re: _roles_ - I am not even sure what roles are, so I can't really provide much comment other than I'd be happy to learn about it and comment if there was an issue created.
