### ISSUE TITLE
Add a -parent option that is -isa + generated -class name

### ISSUE THREAD

**Issue by haukex** [haukex/Util-H2O#9]
```perl
my $o = h2o -parent => 'Foo::Bar', {};
# would be the equivalent of
my $o = h2o -isa => 'Foo::Bar', -class => "Foo::Bar::_$uniqueid", {};
```

Since this idea is stolen from `baptize` in oodler577/p5-Util-H2O-More@66e5b8afdac2900afc64b7f882e4dcac61f1b275, @oodler577, I would like to get your feedback on this if possible (I emailed you about this previously). Also, as I mentioned over in #6, please let me know if and how you would like credit in the documentation!

**Comment by oodler577** [comment]
Oh, very nice! Sorry I missed your comms. Credit would be appreciated, if only to help gain some "social credit" that others (like myself) find this module incredibly useful. :-)

**Comment by oodler577** [comment]
@haukex please don't hesitate to let me know if there is anything I can assist with - QA or documentation, etc. Looking forward to this and 0.18.

**Comment by haukex** [comment]
Thanks for the offer! I'm currently fairly busy but I hope to get to the implementation in the next couple of weeks.

**Comment by oodler577** [comment]
I the lates `Util::H2O::More`, I deprecated `baptise_deeply` and favor of supporting `baptise -recurse, ...`.

I also added `o2h` and `o2h -recurse`, that will return the _unblessed_ form of the object; in the case of `-recurse`, it will walk the datastructure and unbless any members that are also blessed. This really cleaned up a lot of my code where I was needed to serialize the structure to send as JSON. I'll send you privately the end result from a real world script.

**Comment by haukex** [comment]
So I've been thinking about this and now am no longer sure whether it makes sense to implement this. Here's my thoughts: `-class => "Foo::Bar::_$uniqueid"` means stepping into another distribution's namespace as far as I can tell for no reason other than readability of debugging dumps. The default behavior of using a generated package name in `Util::H2O::_*` provides the same functionality, and has the advantage that `h2o` objects remain easily identifiable by their package name. So if we assume for a minute that the `-class` option isn't necessary, then the feature I proposed above already exists, namely `-isa`.

But perhaps I am missing something in the motivation behind `baptise`?

(Side note: I do think it's worth it to change the effect of the `-isa` option and add the calling of the superclass' `DESTROY`).

**Comment by oodler577** [comment]
The reason I created `baptise` was to be able to create a drop in replacement for `bless` that gives you accessors and allows for a proper OOP module constructor. I do not think that underlying support via `h2o` is really needed - since I'd still have to use the new switches underneath providing what I actually wanted (which is what `baptise` does in function and the idiom supported). You can close this if you don't think you want to do it. 100% up to you.

**Comment by haukex** [comment]
It's not that it's not a good feature, it's just that at the moment I see too much similarity to the existing `-isa` to make implementing a new option worth it - the issue is that with each new option, I should be testing its interaction with other options, which would make the number of tests grow exponentially.

In the meantime, I've had a new idea with how I might be able to modify the behavior of the `-class` option to make it do something that gets close to what `baptise` does, but I need to think about this some more.
